export interface MaternityBill {
    maternityBillID: string,
    maternityConfigurationID: string,
    currentMonth: string,
    fromMonth: string,
    toMonth: string,
    numberOfMonths: string,
    basicSalary: number,
    workingDays: number,
    actualCurrentSalary: number,
    earnedLeaveDays: number,
    earnedLeaveAmount: number,
    computed3MonthNetPayable: number,
    computed3MonthWorkingDays: number,
    actualPay: number,
    computedPay: number, 
    actualNetPayable: number,
    computedNetPayable: number,
    localAreaClerance: string,
    localAreaRemarks: string,
    approvedDate: string,
    entryDate: string,
    employeeID: string
}
