export class SalaryRecord {

    constructor(
    public salaryRecordID?: string,
    public salaryStartDate?: string,
    public salaryEndDate?: string,
    public joiningDate?: string,
    public monthDays?: number,
    public punchDays?: number,
    public totalHoliDay?: number,
    public totalLeave?: number,
    public workingDays?: number,
    public absenteeism?: number,
    public gross?: number,
    public actualGross?: number,
    public basic?: number,
    public houseRent?: number,
    public medicalAllowance?: number,
    public mobileAllowance?: number,
    public otherAllowances?: number,
    public lunchAllowance?: number,
    public tax?: number,
    public otherDeduction?: number,
    public otHours?: number,
    public otAmount?: number,
    public byBankAmount?: number,
    public byCashAmount?: number,
    public netPayable?: number,
    public conveyanceAllowance?: number,
    public attendanceBonus?: number,
    public specialAllowance?: number,
    public salaryAdvance?: number,
    public foodCharge?: number,
    public otRate?: number,
    public tiffinAllowance?: number,
    public arrear?: number,
    public specialBonus?: number,
    public leaveStatus?: string,
    public holiDayBillAmount?: number,
    public nightBillAmount?: number,
    public salaryID?: number,
    public lunchBillAmount?: number,
    public mobileBanking?: boolean,
    public accountNumber?: string,
    public bankName?: string,
    public processDate?: string,
    public unitID?: string,
    public sectionID?: string,
    public employmentTypeID?: string,
    public salaryGradeID?: string,
    public companyID?: string,
    public departmentID?: string,
    public designationID?: string,
    public gradeID?: string
  ) {}
}
